# This is a basic workflow to help you get started with Actions

name: CI

on: 
  push:
    branches: '**'

jobs:
  build-job:
    runs-on: ${{ matrix.os }}
    name: "Build and test ${{ matrix.os }}"
    strategy:
      matrix:
        os: [ubuntu-latest]
      
    steps:
    - name: "Setup node"
      uses: actions/setup-node@v1
      with:
        node-version: '15'
    - name: "Checkout source code"
      uses: "actions/checkout@v2"
    - name: "Install modules"
      run: "npm install"
    - name: "Build (npm)"
      run: "npm run build"
    - name: "Test"
      run: "npm run test"
